### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by dicethrower** [thedarkcolour/KotlinModdingSkeleton#2]
I tried to build this project in intellij idea and got this error

Error:(40, 17) Kotlin: Type inference failed: inline fun <T : GenericEvent<out F>, reified F> addGenericListener(consumer: Consumer<T>): Unit
cannot be applied to
(KFunction1<@ParameterName RegistryEvent.Register<Block>, Unit>)
Error:(40, 36) Kotlin: Type mismatch: inferred type is KFunction1<@ParameterName RegistryEvent.Register<Block>, Unit> but Consumer<???> was expected

**Comment by thedarkcolour** [comment]
Should be fixed now that Kotlin 1.4 is out of pre release
